use_default_settings:
  engines:
    remove:
      - ahmia
      - google
      - torch

general:
  instance_name: "LibreChat Local Search"
  debug: false
  enable_metrics: false
  open_metrics: ""

search:
  safe_search: 1
  formats:
    - html
    - json

outgoing:
  request_timeout: 4.0
  proxies:
    all://:
      - http://egress-proxy:3128

server:
  base_url: http://searxng:8080/
  limiter: true
  image_proxy: false

valkey:
  url: valkey://searxng-valkey:6379/0

ui:
  static_use_hash: true
